name: Deploy FrontEnd - Google Cloud Run

on:
  push:
    branches:
      - test-sonar

env:
  CLOUD_RUN_PROJECT_ID: lattice
  CLOUD_RUN_REGION: us-central1
  # project-name but it can be anything you want
  REPO_NAME: lattice-client

jobs:
  build-and-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and tag image
      run: |-
        docker build -f . --build-arg GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} \
          --build-arg MAPBOX_API_KEY=${{ secrets.MAPBOX_API_KEY }} --tag "gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA"
        docker tag "gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA" "gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:latest"

    - name: Push image to GCR
      run: |-
        docker push gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA
        docker push gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:latest

    - name: Deploy
      run: |-
        gcloud components install beta --quiet
        gcloud run deploy $REPO_NAME --image gcr.io/$CLOUD_RUN_PROJECT_ID/$REPO_NAME:$GITHUB_SHA \
          --project $CLOUD_RUN_PROJECT_ID \
          --platform managed \
          --region $CLOUD_RUN_REGION \
          --allow-unauthenticated \
          --quiet